# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur_arm_controller
    - ur_hand_controller

  ur_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
    action_ns: follow_joint_trajectory
    default: true
  ur_hand_controller:
    type: GripperCommand
    joints:
      - wrist_3_joint
    action_ns: gripper_cmd
    default: true